name: ci

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 1 * *'

jobs:
  cabal:
    runs-on: ubuntu-latest
    name: hsc3
    steps:
      - uses: actions/checkout@v2
      - uses: haskell/actions/setup@v1
      - run: cabal update
      - run: cabal build
